### ISSUE TITLE
also just a warning

### ISSUE THREAD

**Issue by irefl** [BillardDRP/tf2spellmarket#5]
you really should hold off on the gh-pages branch until it actually works also if this is a thing than we are going to need sql..... shit

**Comment by SirFrancisBillard** [comment]
shut up it can work

**Comment by SirFrancisBillard** [comment]
jkjk but rly imma do it

**Comment by SirFrancisBillard** [comment]
it works okayish...
https://billarddrp.github.io/tf2spellmarket/

**Comment by irefl** [comment]
not realllllyyyy its just the header and nothing esle

**Comment by SirFrancisBillard** [comment]
It wasn't supposed to be. I am updating it with pages and all is well.

**Comment by SirFrancisBillard** [comment]
pidar blyat
